import type { theme_palette, theme_styles } from "@twinkleplop/core";

/**
 * Nord for twinkleplop (local theme, not an upstream package).
 *
 * Token colors are copied verbatim from the official arcticicestudio
 * Nord VS Code theme (`nord` tokenColors, dark): Frost `#81A1C1` for
 * keywords/operators/tags, `#88C0D0` for functions/headings/links,
 * `#8FBCBB` for types/classes/attributes, `#5E81AC` for directives;
 * Aurora `#A3BE8C` strings, `#EBCB8B` regex/escapes/diffs-changed,
 * `#BF616A` diffs-deleted, `#B48EAD` numbers, `#D08770` decorators;
 * Snow Storm `#D8DEE9` base text / `#ECEFF4` punctuation; Polar Night
 * `#616E88` comments. Dark bg `#2E3440`.
 *
 * Keys with no direct TextMate scope use the closest analog: component
 * tag names follow the teal `entity.name.type` rule, JSX props the teal
 * `entity.name.tag`-adjacent attribute rule, object-literal keys and
 * units fall back to base text, template expressions and `#` sigils
 * follow the blue template-punctuation rule, task markers and prompt
 * prefixes follow the frost family. Markdown emphasis keeps no extra
 * style beyond the token color: the reference specifies `fontStyle`
 * only for emphasis/strong/italic/underline, so — unlike Everforest —
 * comments and headings render upright here.
 *
 * The reference ships dark only, but twinkleplop themes always carry
 * both variants: light reuses the exact same hues on Snow Storm
 * (`background_color` `#ECEFF4`, base text `#2E3440`), the way upstream
 * Nord reuses hues across ambiances. Identifiers stay one step off
 * base text (`#D8DEE9` dark / `#3B4252` light) and muted markers use
 * `#616E88` dark / `#4C566A` light.
 *
 * Fidelity is intentional: several official tokens sit below WCAG AA
 * (dark comments, frost blues on snow), so this family is exempt from
 * contrast tests and pinned by reference instead — see
 * `registry.test.ts`. Tag names resolve to the blue `tag` entry and JSX
 * brackets/terminators to the blue `operator` entry via `token-roles.ts`
 * (matching `entity.name.tag`, `punctuation.definition.tag`, and
 * `punctuation.terminator`); everything else keeps its raw grammar role.
 */

export const light: theme_palette = {
  array_table_header: "#8fbcbb",
  attr_name: "#8fbcbb",
  attr_sigil: "#81a1c1",
  attribute: "#8fbcbb",
  autolink: "#88c0d0",
  autolink_close: "#88c0d0",
  autolink_open: "#88c0d0",
  background_color: "#eceff4",
  bit: "#b48ead",
  block_scalar_header: "#8fbcbb",
  blockquote_marker: "#4c566a",
  bold: "#2e3440",
  bold_close: "#2e3440",
  bold_open: "#2e3440",
  boolean: "#81a1c1",
  builtin: "#88c0d0",
  carriage_return: "inherit",
  changed: "#ebcb8b",
  changed_marker: "#ebcb8b",
  class_name: "#8fbcbb",
  code: "#8fbcbb",
  code_block: "#2e3440",
  code_close: "#8fbcbb",
  code_fence: "#8fbcbb",
  code_language: "#8fbcbb",
  code_open: "#8fbcbb",
  comment: "#4c566a",
  constant: "#81a1c1",
  css_variable: "#2e3440",
  datetime: "#b48ead",
  decorator: "#d08770",
  deleted: "#bf616a",
  deleted_marker: "#bf616a",
  directive: "#5e81ac",
  doc_marker: "#4c566a",
  doctype: "#5e81ac",
  entity: "#ebcb8b",
  escape: "#ebcb8b",
  expression: "#81a1c1",
  format: "#a3be8c",
  front_matter_marker: "#4c566a",
  function: "#88c0d0",
  hard_break: "#4c566a",
  hash: "#81a1c1",
  heading: "#88c0d0",
  heading_marker: "#81a1c1",
  hr: "#4c566a",
  identifier: "#3b4252",
  inserted: "#a3be8c",
  inserted_marker: "#a3be8c",
  italic: "#2e3440",
  italic_close: "#2e3440",
  italic_open: "#2e3440",
  keyword: "#81a1c1",
  label: "#8fbcbb",
  lifetime: "#8fbcbb",
  link_text: "#88c0d0",
  link_text_close: "#88c0d0",
  link_text_open: "#88c0d0",
  list_marker: "#81a1c1",
  namespace: "#8fbcbb",
  newline: "inherit",
  null: "#81a1c1",
  number: "#b48ead",
  operator: "#81a1c1",
  output: "#2e3440",
  parameter: "#3b4252",
  plain_scalar: "#a3be8c",
  prompt: "#2e3440",
  prompt_prefix: "#8fbcbb",
  property: "#2e3440",
  punctuation: "#2e3440",
  raw_code_block: "#2e3440",
  raw_front_matter: "#2e3440",
  raw_json: "#2e3440",
  raw_markup: "#2e3440",
  raw_script: "#2e3440",
  raw_shell: "#2e3440",
  raw_style: "#2e3440",
  raw_svelte_expression: "#2e3440",
  regex: "#ebcb8b",
  selector: "#81a1c1",
  selector_class: "#8fbcbb",
  selector_id: "#8fbcbb",
  selector_pseudo: "#81a1c1",
  space: "inherit",
  strike: "#4c566a",
  strike_close: "#4c566a",
  strike_open: "#4c566a",
  string: "#a3be8c",
  string_escape: "#ebcb8b",
  svelte_block: "#81a1c1",
  svelte_directive: "#8fbcbb",
  tab: "inherit",
  tag: "#81a1c1",
  tag_name: "#8fbcbb",
  task_marker: "#88c0d0",
  template: "#a3be8c",
  type: "#8fbcbb",
  unit: "#2e3440",
  url: "#88c0d0",
  url_link: "#88c0d0",
  url_title: "#88c0d0",
  variable: "#3b4252",
  variant: "#8fbcbb",
};

export const dark: theme_palette = {
  array_table_header: "#8fbcbb",
  attr_name: "#8fbcbb",
  attr_sigil: "#81a1c1",
  attribute: "#8fbcbb",
  autolink: "#88c0d0",
  autolink_close: "#88c0d0",
  autolink_open: "#88c0d0",
  background_color: "#2e3440",
  bit: "#b48ead",
  block_scalar_header: "#8fbcbb",
  blockquote_marker: "#616e88",
  bold: "#d8dee9",
  bold_close: "#d8dee9",
  bold_open: "#d8dee9",
  boolean: "#81a1c1",
  builtin: "#88c0d0",
  carriage_return: "inherit",
  changed: "#ebcb8b",
  changed_marker: "#ebcb8b",
  class_name: "#8fbcbb",
  code: "#8fbcbb",
  code_block: "#d8dee9",
  code_close: "#8fbcbb",
  code_fence: "#8fbcbb",
  code_language: "#8fbcbb",
  code_open: "#8fbcbb",
  comment: "#616e88",
  constant: "#81a1c1",
  css_variable: "#d8dee9",
  datetime: "#b48ead",
  decorator: "#d08770",
  deleted: "#bf616a",
  deleted_marker: "#bf616a",
  directive: "#5e81ac",
  doc_marker: "#616e88",
  doctype: "#5e81ac",
  entity: "#ebcb8b",
  escape: "#ebcb8b",
  expression: "#81a1c1",
  format: "#a3be8c",
  front_matter_marker: "#616e88",
  function: "#88c0d0",
  hard_break: "#616e88",
  hash: "#81a1c1",
  heading: "#88c0d0",
  heading_marker: "#81a1c1",
  hr: "#616e88",
  identifier: "#d8dee9",
  inserted: "#a3be8c",
  inserted_marker: "#a3be8c",
  italic: "#d8dee9",
  italic_close: "#d8dee9",
  italic_open: "#d8dee9",
  keyword: "#81a1c1",
  label: "#8fbcbb",
  lifetime: "#8fbcbb",
  link_text: "#88c0d0",
  link_text_close: "#88c0d0",
  link_text_open: "#88c0d0",
  list_marker: "#81a1c1",
  namespace: "#8fbcbb",
  newline: "inherit",
  null: "#81a1c1",
  number: "#b48ead",
  operator: "#81a1c1",
  output: "#d8dee9",
  parameter: "#d8dee9",
  plain_scalar: "#a3be8c",
  prompt: "#d8dee9",
  prompt_prefix: "#8fbcbb",
  property: "#d8dee9",
  punctuation: "#eceff4",
  raw_code_block: "#d8dee9",
  raw_front_matter: "#d8dee9",
  raw_json: "#d8dee9",
  raw_markup: "#d8dee9",
  raw_script: "#d8dee9",
  raw_shell: "#d8dee9",
  raw_style: "#d8dee9",
  raw_svelte_expression: "#d8dee9",
  regex: "#ebcb8b",
  selector: "#81a1c1",
  selector_class: "#8fbcbb",
  selector_id: "#8fbcbb",
  selector_pseudo: "#81a1c1",
  space: "inherit",
  strike: "#616e88",
  strike_close: "#616e88",
  strike_open: "#616e88",
  string: "#a3be8c",
  string_escape: "#ebcb8b",
  svelte_block: "#81a1c1",
  svelte_directive: "#8fbcbb",
  tab: "inherit",
  tag: "#81a1c1",
  tag_name: "#8fbcbb",
  task_marker: "#88c0d0",
  template: "#a3be8c",
  type: "#8fbcbb",
  unit: "#d8dee9",
  url: "#88c0d0",
  url_link: "#88c0d0",
  url_title: "#88c0d0",
  variable: "#d8dee9",
  variant: "#8fbcbb",
};

export const light_styles: theme_styles = {
  autolink: ["underline"],
  bold: ["bold"],
  italic: ["italic"],
  strike: ["strikethrough"],
};

export const dark_styles: theme_styles = {
  autolink: ["underline"],
  bold: ["bold"],
  italic: ["italic"],
  strike: ["strikethrough"],
};
