import {
  FileTextIcon,
  KeyboardIcon,
  ListTreeIcon,
  SparklesIcon,
} from "lucide-react";

export const DEFAULT_PLACEHOLDER =
  "Type / for commands, or just start writing...";

export const WORD_SEPARATOR_PATTERN = /\s+/;

export const FEATURE_ITEMS = [
  {
    icon: SparklesIcon,
    label: "Slash commands",
    description: "Quick insert menu inspired by Notion.",
  },
  {
    icon: KeyboardIcon,
    label: "Markdown shortcuts",
    description: "Type #, -, > and more to format while writing.",
  },
  {
    icon: ListTreeIcon,
    label: "Block toolbar",
    description: "Change block type, alignment and indentation fast.",
  },
  {
    icon: FileTextIcon,
    label: "Markdown export",
    description: "Always keep HTML, markdown and plain text in sync.",
  },
] as const;

export const DEFAULT_EDITOR_MARKDOWN = [
  "# Welcome to Pytah",
  "",
  "A **copy-paste-ready** editor built with [Lexical](https://lexical.dev), shadcn and Base UI. Everything below was loaded from a single markdown string.",
  "",
  "## Rich text formatting",
  "",
  "Highlight any text to open the floating toolbar, or use markdown shortcuts while you type:",
  "",
  "- **Bold text** with `**double asterisks**`",
  "- *Italic text* with `*single asterisks*`",
  "- ~~Strikethrough~~ with `~~tildes~~`",
  "- ==Highlighted text== with `==double equals==`",
  "- `Inline code` with `` `backticks` ``",
  "- [Links](https://github.com) with `[text](url)`",
  "",
  "## Block types",
  "",
  "### Bullet lists",
  "",
  "- First item with some detail",
  "- Second item — lists support **rich** *formatting* too",
  "- Third item",
  "",
  "### Numbered lists",
  "",
  "1. Open the slash command menu by typing `/`",
  "1. Pick a block type from the list",
  "1. Keep writing — the block converts instantly",
  "",
  "### Checklists",
  "",
  "- [x] Set up the editor",
  "- [x] Add slash commands",
  "- [ ] Ship to production",
  "",
  "> **Tip:** Type `>` at the start of a line for a blockquote, or `---` for a divider.",
  "",
  "---",
  "",
  "## Code blocks",
  "",
  "Fenced code blocks support syntax highlighting. Type ` ``` ` followed by a language hint:",
  "",
  "```tsx",
  'import { Editor } from "@/components/editor/editor";',
  "",
  "export function App() {",
  "  return <Editor editable />;",
  "}",
  "```",
  "",
  "## Tables",
  "",
  "| Feature | Shortcut | Status |",
  "| --- | --- | --- |",
  "| Headings | `# `, `## `, `### ` | Ready |",
  "| Lists | `- `, `1. `, `- [ ] ` | Ready |",
  "| Code blocks | ` ``` ` | Ready |",
  "| Images | `![alt](url)` | Ready |",
  "| Tables | Markdown GFM syntax | Ready |",
  "",
  "## Images",
  "",
  "![Pytah editor](https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80)",
  "",
  "## More blocks",
  "",
  "Type `/` on an empty line to insert **collapsible toggles**, **multi-column layouts**, **YouTube embeds**, and more. The slash menu supports fuzzy search — try `/col` or `/vid`.",
  "",
  "---",
  "",
  "*Built with Lexical, shadcn, Base UI and Tailwind CSS v4.*",
].join("\n");

export const MARKDOWN_EXAMPLE = [
  "# Markdown import",
  "",
  "Paste markdown here and keep editing visually.",
  "",
  "- bullet one",
  "- bullet two",
  "",
  "```ts",
  "const ready = true;",
  "```",
].join("\n");

export const HTML_EXAMPLE = [
  "<h1>Imported HTML</h1>",
  "<p>This content was inserted as HTML and normalized by Lexical.</p>",
  "<ul><li>Lists stay editable</li><li>Formatting remains semantic</li></ul>",
  "<blockquote>Great editors should be easy to paste into and out of.</blockquote>",
].join("");
